import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          `antialiased vsc-initialized`,
          'bg-slate-50 dark:bg-[#313338] h-full'
        )
        }
      >
        <ThemeProvider
          attribute='class'
          defaultTheme="dark"
          enableSystem={true}
          storageKey="='discord-theme"
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
