import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { cn } from "@/lib/utils";
import { ModalProvider } from "@/components/providers/modal-provider";
import { Inter } from 'next/font/google'

export const metadata: Metadata = {
  title: "Kinesh Lohar",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          `antialiased vsc-initialized ${inter.variable}`,
          'bg-slate-50 dark:bg-black h-full'
        )
        }
      >
        <ThemeProvider
          attribute='class'
          defaultTheme="dark"
          enableSystem={true}
          storageKey="='discord-theme"
        >
          <ModalProvider />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
