import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { cn } from "@/lib/utils";
import { ModalProvider } from "@/components/providers/modal-provider";
import { Bree_Serif, Eagle_Lake, Inter, Lato, Sriracha } from 'next/font/google'

export const metadata: Metadata = {
  title: "Kinesh Lohar",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

const breeserif = Bree_Serif({
  subsets: ['latin'],
  weight: "400",
  variable: '--font-breeserif',
})

const eaglelake = Eagle_Lake({
  weight: "400",
  subsets: ['latin'],
  fallback: ['var(--font-breeserif)', 'serif'],
  variable: '--font-eaglelake'
})

const lato = Lato({
  weight: "400",
  subsets: ['latin'],
  fallback: ['var(--font-lato)', 'serif'],
  variable: '--font-lato'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning
    className={`${inter.className} ${breeserif.variable} ${eaglelake.variable} ${lato.variable}`}
    >
      <body
        className={cn(
          `antialiased vsc-initialized `,
          'bg-slate-50 dark:bg-black min-h-screen scroll-smooth'
        )
        }
      >
        <ThemeProvider
          attribute='class'
          defaultTheme="dark"
          enableSystem={true}
          storageKey="='discord-theme"
        >
          <ModalProvider />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
